{
 "title": "PSPDFKit Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Scheduler utilisation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vm_scheduler_wall_time",
     "query": "SELECT (mean(\"active_upper\")/mean(\"total_upper\")) FROM \"vm_scheduler_wall_time\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vm_memory",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP performance 90pp (without long poll)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "status=[[tag_status]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server",
     "select": [
      [
       { "params": [ "req_end_90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "family", "operator": "=", "value": "pspdfkit-server" },
      { "condition": "AND", "key": "group", "operator": "=", "value": "standard" }
     ]
    }
   ]
  },
  {
   "title": "Remote documents fetch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Response start",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "remote_doc",
     "select": [
      [
       { "params": [ "response_start_90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Response end",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "remote_doc",
     "select": [
      [
       { "params": [ "response_end_90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FS Cache - Hit vs. Miss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Hit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "cache",
     "select": [
      [
       { "params": [ "fs_hit" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "family", "operator": "=", "value": "pspdfkit-server" }
     ]
    },
    {
     "alias": "Miss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "cache",
     "select": [
      [
       { "params": [ "fs_miss" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "family", "operator": "=", "value": "pspdfkit-server" }
     ]
    }
   ]
  },
  {
   "title": "FS Cache - Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Total size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cache",
     "select": [
      [
       { "params": [ "fs_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "family", "operator": "=", "value": "pspdfkit-server" }
     ]
    }
   ]
  },
  {
   "title": "Instant Sync Processing time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Total 90 percentile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "layer.sync",
     "select": [
      [
       { "params": [ "total_90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Libreoffice conversion time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Success duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "document_conversion",
     "select": [
      [
       { "params": [ "convert_90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "success" }
     ]
    },
    {
     "alias": "Error duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "document_conversion",
     "select": [
      [
       { "params": [ "convert_90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "success" }
     ]
    }
   ]
  },
  {
   "title": "Postgres performance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "query time 90pp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg_client",
     "query": "SELECT (mean(\"query_90_percentile\") + mean(\"queue_90_percentile\") + mean(\"decode_90_percentile\")) FROM \"pg_client\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "decode_90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "family", "operator": "=", "value": "pspdfkit-server" }
     ]
    }
   ]
  }
 ]
}